src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>TotalPriceWithDiscount__c</fullName>
        <formula>TotalPrice__c * (1- Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price With Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DailyIncome__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Income__c</fullName>
        <label>Income</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Daily Income</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Income</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Archivator.cls
public class Archivator implements Schedulable {

    public void execute(SchedulableContext param1) {
        Savepoint archivationFailed = Database.setSavepoint();
        try {
            Map<Date, Decimal> dayToIncome = new Map<Date, Decimal>();
            List<Bill__c> bills = [SELECT TotalPriceWithDiscount__c, createddate
            FROM Bill__c WHERE Archived__c = false];
            for (Bill__c b : bills) {
                if (!dayToIncome.containsKey(b.createddate.date())) {
                    dayToIncome.put(b.createddate.date(), 0);
                }
                b.Archived__c = true;
                dayToIncome.put(b.createddate.date(), dayToIncome.get(b.createddate.date())+ b.TotalPriceWithDiscount__c);
            }
            update bills;

            List<DailyIncome__c> dailyIncome = new List<DailyIncome__c>();
            for (Date day : dayToIncome.keySet()) {
                dailyIncome.add(new DailyIncome__c(
                        Name = String.valueOf(day),
                        Date__c = day,
                        Income__c = dayToIncome.get(day)
                ));

            }
            insert dailyIncome;
        } catch (Exception e) {
            Database.rollback(archivationFailed);
            TheMostAbstractUtility.logException('Archivator', e);
            throw e;
        }
    }

    /** Execute to achieve all
    List<DailyIncome__c> dailyIncome = new List<DailyIncome__c>();
    for (AggregateResult ar :  [
            SELECT sum(TotalPriceWithDiscount__c) dayIncome, DAY_ONLY(createddate) date
            FROM Bill__c
            GROUP BY DAY_ONLY(createddate)]) {
        Date day = (Date)ar.get('date');
        dailyIncome.add(new DailyIncome__c(
                Name = String.valueOf(day),
                Date__c = day,
                Income__c = (Decimal)ar.get('dayIncome')
        ));
    }
    insert dailyIncome;
    */
}