src/objects/Bill__c.object
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GarbageCollector.cls
public class GarbageCollector implements Schedulable {

    public void execute(SchedulableContext param1) {
        try {
            delete [SELECT Id FROM Bill__c WHERE Archived__c = true AND createddate != LAST_N_DAYS:20];
        } catch (Exception e) {
            saveLog(e.getMessage() + ' ' + e.getStackTraceString());
            throw e;
        }
    }

    @future
    private static void saveLog(String error) {
        insert new Log__c(Error__c = error);
    }
}