src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>TotalPriceWithDiscount__c</fullName>
        <formula>TotalPrice__c * (1- Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price With Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Reporting.cls
public class Reporting implements Schedulable, Database.AllowsCallouts {

    public void execute(SchedulableContext param1) {
        try {
            Decimal dailyTotal = getDailyTotal();
            new TelegramReporter().sendDailyTotal(dailyTotal);
        } catch (Exception e) {
            TheMostAbstractUtility.logException('Reporting.execute: ', e);
        }
    }

    private static Decimal getDailyTotal() {
        AggregateResult result = [SELECT sum(TotalPriceWithDiscount__c) dailyTotal FROM Bill__c WHERE CreatedDate = TODAY];
        return result.get('dailyTotal') == null ? 0 : (Decimal)result.get('dailyTotal');
    }
}