src/objects/Bill__c.object
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductBill__c.object
<CustomObject>
    <fields>
        <fullName>Bill__c</fullName>
        <label>Bill</label>
        <referenceTo>Bill__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductBills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Bill</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewBillController.cls
public with sharing class NewBillController {
    @AuraEnabled
    public static void saveBillWithProducts(Bill__c bill, List<ProductBill__c> billProducts) {
        Savepoint noProductsNoBillSavepoint = Database.setSavepoint();
        try {
            insert bill;

            for (ProductBill__c productBill : billProducts) {
                productBill.Bill__c = bill.Id;
            }
            insert billProducts;

        } catch(Exception e) {
            Database.rollback(noProductsNoBillSavepoint);
            saveLog(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @future
    private static void saveLog(String error) {
        insert new Log__c(Error__c = error);
    }

}