src/objects/Bill__c.object
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductBill__c.object
<CustomObject>
    <fields>
        <fullName>Bill__c</fullName>
        <label>Bill</label>
        <referenceTo>Bill__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductBills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Bill</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewBillControllerTest.cls
@isTest
private class NewBillControllerTest {

    @isTest
    private static void testSuccess() {
        Bill__c bill = new Bill__c();
        List<ProductBill__c> billProducts = new List<ProductBill__c>();

        Test.startTest();
            NewBillController.saveBillWithProducts(bill, billProducts);
        Test.stopTest();

        System.assertEquals(1, [select count() from Bill__c]);
    }

    @isTest
    private static void testFailure() {
        Bill__c bill = new Bill__c();
        List<ProductBill__c> billProducts = new List<ProductBill__c> {
                new ProductBill__c()
        };

        Test.startTest();
            try{
                NewBillController.saveBillWithProducts(bill, billProducts);
                System.assert(false, 'Should be an exception');
            } catch (AuraHandledException e) {}
        Test.stopTest();

        System.assertEquals(0, [select count() from Bill__c], 'Should be rolled back');
    }
}