src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hot Drinks</fullName>
                    <default>true</default>
                    <label>Hot Drinks</label>
                </value>
                <value>
                    <fullName>Cold Drinks</fullName>
                </value>
                <value>
                    <fullName>Eats</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductSelectorController.cls
public with sharing class ProductSelectorController {

    @AuraEnabled(cacheable=true)
    public static Map<String, List<Product>> getProductsBySection() {
        try {
            return getSectionToProducts();
        } catch (Exception e) {
            saveLog(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static Map<String, List<Product>> getSectionToProducts() {
        Map<String, List<Product>> sectionToProducts = new Map<String, List<Product>>();
        for (Product__c product : [SELECT Name, Cost__c, Type__c, Picture__c, Description__c
        FROM Product__c
        WHERE Active__c = true
        ORDER BY Type__c, Name]) {
            if (!sectionToProducts.containsKey(product.Type__c)) {
                sectionToProducts.put(product.Type__c, new List<Product>());
            }
            sectionToProducts.get(product.Type__c).add(new Product(product));
        }
        return sectionToProducts;
    }

    @future
    private static void saveLog(String error) {
        insert new Log__c(Error__c = error);
    }

    public class Product {
        @AuraEnabled public String productId;
        @AuraEnabled public String name;
        @AuraEnabled public String description;
        @AuraEnabled public Decimal cost;
        @AuraEnabled public String picture;

        public Product(Product__c product) {
            this.name = product.Name;
            this.description = product.Description__c;
            this.cost = product.Cost__c;
            this.picture = product.Picture__c;
            this.productId = product.Id;
        }
    }
}