src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MotivationalQuote__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Motivational Quote</label>
</CustomObject>

src/classes/TheMostAbstractUtility.cls
public class TheMostAbstractUtility {

    public static void logException(String whereOccured, Exception e) {
        logError(whereOccured + ':' + e.getMessage() + ' ' + e.getStackTraceString());
    }

    @future
    public static void logError(String error) {
        insert new Log__c(Error__c = error);
    }

    public static String getRandomQuote() {
        Integer countQuotes = [SELECT count() from MotivationalQuote__c];
        if (countQuotes == 0) {
            return '';
        }
        Integer randomQuote = Math.floor(Math.random() * countQuotes).intValue();
        return [SELECT Quote__c FROM MotivationalQuote__c LIMIT 1 OFFSET :randomQuote].Quote__c;
    }
}